// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyDxyT-TYFJiK3GE0ZLw1zi2pyyeVYIA0',
    appId: '1:437104823640:web:78abec4c757029359de92d',
    messagingSenderId: '437104823640',
    projectId: 'web-projects-42e93',
    authDomain: 'web-projects-42e93.firebaseapp.com',
    storageBucket: 'web-projects-42e93.appspot.com',
    measurementId: 'G-WKSX94HMSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDlWvoMiVykUJSgIGASzA1aju6ycGTjg',
    appId: '1:437104823640:android:a85fdd217c232c679de92d',
    messagingSenderId: '437104823640',
    projectId: 'web-projects-42e93',
    storageBucket: 'web-projects-42e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIc458k5mGdoEFyEyzyOPrFxb9lA664sQ',
    appId: '1:437104823640:ios:d76822bc6cfb2e079de92d',
    messagingSenderId: '437104823640',
    projectId: 'web-projects-42e93',
    storageBucket: 'web-projects-42e93.appspot.com',
    iosClientId: '437104823640-qcfbq2ln81ukkn97qfd44m9fetcniiog.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIc458k5mGdoEFyEyzyOPrFxb9lA664sQ',
    appId: '1:437104823640:ios:d76822bc6cfb2e079de92d',
    messagingSenderId: '437104823640',
    projectId: 'web-projects-42e93',
    storageBucket: 'web-projects-42e93.appspot.com',
    iosClientId: '437104823640-qcfbq2ln81ukkn97qfd44m9fetcniiog.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmpro',
  );
}
